from __future__ import annotations

import json
import os
import time
from pathlib import Path
from typing import Any, Iterable


AUTH_COOKIE_NAME = "dbcl2"
CSRF_COOKIE_NAME = "ck"


def ensure_private_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    try:
        os.chmod(path, 0o700)
    except OSError:
        pass


def write_private_text(path: Path, content: str) -> None:
    ensure_private_dir(path.parent)
    path.write_text(content, encoding="utf-8")
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass


def write_private_json(path: Path, data: Any) -> None:
    write_private_text(path, json.dumps(data, ensure_ascii=False, indent=2) + "\n")


def has_auth_cookie(cookies: Iterable[dict[str, Any]]) -> bool:
    return any(cookie.get("name") == AUTH_COOKIE_NAME and cookie.get("value") for cookie in cookies)


def cookie_names(cookies: Iterable[dict[str, Any]]) -> list[str]:
    return sorted({str(cookie.get("name")) for cookie in cookies if cookie.get("name")})


def douban_cookies(cookies: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    return [
        cookie
        for cookie in cookies
        if "douban.com" in str(cookie.get("domain", "")).lstrip(".")
    ]


def cookie_header(cookies: Iterable[dict[str, Any]]) -> str:
    pairs: list[tuple[str, str]] = []
    now = time.time()
    seen: set[str] = set()
    for cookie in douban_cookies(cookies):
        name = str(cookie.get("name", ""))
        value = str(cookie.get("value", ""))
        if not name or name in seen:
            continue
        expires = cookie.get("expires")
        if isinstance(expires, (int, float)) and expires > 0 and expires < now:
            continue
        seen.add(name)
        pairs.append((name, value))
    return "; ".join(f"{name}={value}" for name, value in sorted(pairs))


def netscape_cookie_file(cookies: Iterable[dict[str, Any]]) -> str:
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by douban-cli. Keep this file private.",
    ]
    for cookie in douban_cookies(cookies):
        domain = str(cookie.get("domain", ""))
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = str(cookie.get("path", "/"))
        secure = "TRUE" if cookie.get("secure") else "FALSE"
        expires = cookie.get("expires")
        if not isinstance(expires, (int, float)) or expires < 0:
            expires = 0
        name = str(cookie.get("name", ""))
        value = str(cookie.get("value", ""))
        if not domain or not name:
            continue
        lines.append(
            "\t".join(
                [
                    domain,
                    include_subdomains,
                    path,
                    secure,
                    str(int(expires)),
                    name,
                    value,
                ]
            )
        )
    return "\n".join(lines) + "\n"


def save_cookie_exports(
    cookies: list[dict[str, Any]],
    cookies_path: Path,
    header_path: Path,
    netscape_path: Path,
) -> None:
    write_private_json(cookies_path, douban_cookies(cookies))
    write_private_text(header_path, cookie_header(cookies) + "\n")
    write_private_text(netscape_path, netscape_cookie_file(cookies))
